from io import BytesIO
from flask import Blueprint, send_file, jsonify
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from models import Payment

receipts_bp = Blueprint("receipts", __name__, url_prefix="/api/receipts")

@receipts_bp.get("/<reference>.pdf")
def receipt_pdf(reference: str):
    p = Payment.query.filter_by(reference=reference).first()
    if not p:
        return jsonify({"error": "Not found"}), 404

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, h - 60, "Departmental Dues Receipt")

    c.setFont("Helvetica", 11)
    y = h - 110
    lines = [
        ("Receipt Ref:", p.reference),
        ("Student:", f"{p.student.name} ({p.student.student_id})"),
        ("Program/Level:", f"{p.student.program} / {p.student.level}"),
        ("Due:", p.assigned_due.due.title),
        ("Amount:", f"GH₵ {p.amount}"),
        ("Method:", p.method),
        ("Status:", p.status),
        ("Date:", p.created_at.isoformat()),
    ]
    for k, v in lines:
        c.drawString(50, y, k)
        c.drawString(170, y, str(v))
        y -= 18

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 60, "Generated by Departmental Dues Payment App")
    c.showPage()
    c.save()

    buf.seek(0)
    return send_file(
        buf,
        mimetype="application/pdf",
        as_attachment=False,  # ✅ opens in browser for printing
        download_name=f"receipt-{reference}.pdf"
    )
